# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CampusStory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
  ]
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Pods for CampusStory
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'SDWebImage/WebP'

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  # pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'
  target 'CampusStory-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CampusStoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
